---
version: "3.8"

services:
  client:
    image: node:20.0.0-alpine
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node

  server:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node
    depends_on:
      - mongo
      - postgres
    environment:
      PORT: 8000
      MONGO_URL: mongodb://root:password@mongo:27017/app?authSource=admin
      DATABASE_URL: postgres://root:password@postgres:5432/app
      JWT_SECRET: secret
    
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data: {}
  postgres-data: {}
  
