services:
  client:
    image: node:20.0.0-alpine
    user: node
    working_dir: /home/node
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - 5174:5173
    volumes:
      - ./client:/home/node
    depends_on:
      - server

  server:
    image: node:20.0.0-alpine
    user: node
    working_dir: /home/node
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - 3000:3000
    volumes:
      - ./server:/home/node
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER_OVH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_OVH}
      POSTGRES_DB: ${POSTGRES_DB_OVH}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mongo_data:
